version: '3'

services:
  stac-app:
    container_name: stac-app
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "7000:8000"
    depends_on:
      - database

  stac-browser:
    container_name: stac-browser
    build:
      context: docker/stac-browser
      dockerfile: Dockerfile
    ports:
      - "9090:8080"

  # taken from https://github.com/stac-utils/stac-fastapi/blob/master/docker-compose.yml
  database:
    container_name: stac-db
    image: ghcr.io/stac-utils/pgstac:v0.5.0
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5432:5432"
    command: postgres -N 500
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - stac-browser
    volumes:
      - ./config/nginx/conf.d/stac.conf:/etc/nginx/conf.d/stac.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/provenma/keys/star.crim.ca.pem:/etc/nginx/cert.pem
      # - /home/ubuntu/keys/stac-dev.key.pem:/etc/nginx/privkey.pem
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    entrypoint: sh
    command: -c 'mkdir -p /export/blob && /usr/bin/minio server :9001 /export'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/export

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/blob;
      /usr/bin/mc policy set public myminio/blob;
      /usr/bin/mc policy set download myminio/blob;
      exit 0;
      "

volumes:
  minio:
  postgres:
